import './globals.css'
import { Poppins } from 'next/font/google'
import NavBar from '@/components/Nav/Nav.jsx'

const poppins = Poppins({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  style: ['normal'],
  variable: '--font-poppins'
})

export const metadata = {
  title: 'Registros Diarios',
  description: 'Generated by Siendo Miguel'
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${poppins.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
